# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestinit():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testinit(self):
    self.driver.get("https://vk.com/search?c%5Bgroup%5D=38959783&c%5Bname%5D=1&c%5Bper_page%5D=40&c%5Bphoto%5D=1&c%5Bq%5D=%D0%92%D0%B8%D1%82%D0%B0%D0%BB%D0%B8%D0%B9&c%5Bsection%5D=people")
    self.driver.set_window_size(1050, 708)
    self.driver.execute_script("window.scrollTo(0,1443)")
    self.driver.execute_script("window.scrollTo(0,2275)")
    self.driver.find_element(By.ID, "email").send_keys("79196807740")
    self.driver.find_element(By.ID, "pass").click()
    self.driver.find_element(By.ID, "pass").send_keys("henhaolong@dflbv123")
    self.driver.find_element(By.ID, "pass").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, "#post-38959783_1401498 .post_img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#post-38959783_1401498 .post_img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "a > .flat_button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#public_followers .header_label").click()
    self.driver.execute_script("window.scrollTo(0,200)")
    self.driver.find_element(By.CSS_SELECTOR, ".ui_box_search").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "search_query").send_keys("Виталий")
    self.driver.find_element(By.ID, "search_query").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollTo(0,1474)")
    self.driver.execute_script("window.scrollTo(0,6274)")
    self.driver.execute_script("window.scrollTo(0,12527)")
    self.driver.execute_script("window.scrollTo(0,16943)")
    self.driver.execute_script("window.scrollTo(0,21576)")
    self.driver.execute_script("window.scrollTo(0,26016)")
    self.driver.execute_script("window.scrollTo(0,28469)")
    self.driver.execute_script("window.scrollTo(0,32684)")
    self.driver.execute_script("window.scrollTo(0,35137)")
    self.driver.execute_script("window.scrollTo(0,39348)")
    self.driver.execute_script("window.scrollTo(0,41801)")
    self.driver.execute_script("window.scrollTo(0,45741)")
    self.driver.execute_script("window.scrollTo(0,47956)")
    self.driver.execute_script("window.scrollTo(0,50582)")
    self.driver.execute_script("window.scrollTo(0,54796)")
    self.driver.execute_script("window.scrollTo(0,56881)")
    self.driver.execute_script("window.scrollTo(0,59474)")
    self.driver.execute_script("window.scrollTo(0,63914)")
    self.driver.execute_script("window.scrollTo(0,66057)")
    self.driver.execute_script("window.scrollTo(0,70253)")
    self.driver.execute_script("window.scrollTo(0,72241)")
    self.driver.execute_script("window.scrollTo(0,74351)")
  
